name: deploy-to-gcp
on:
  push: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'
          check-latest: true
      - run: python -m venv .venv
      - run: . venv/bin/activate
      - run: pip install -U -r requirements.txt
          
      
      