name: deploy-to-gcp
on:
  push: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PIP_REQUIRE_VIRTUALENV: true
    permissions:
        contents: read
        id-token: write
    steps:
      - uses: ./.github/actions/setup_dbt
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/472162324340/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-deploy@pypi-408816.iam.gserviceaccount.com'
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      - name: 'dbt build test'
        run: |
          source .venv/bin/activate
          source .envs/test.env
          dbt deps
          dbt debug
          dbt build
      - name: 'dbt build prod'
        run: |
          source .venv/bin/activate
          source .envs/prod.env
          dbt deps
          dbt debug
          dbt build

        
          
      
      