name: deploy-to-gcp
on:
  push: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PIP_REQUIRE_VIRTUALENV: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'
          check-latest: true
      - id: setup-python-venv
        run: |
          python --version
          python -m venv .venv
          source .venv/bin/activate
          echo $PATH
          echo PATH=$PATH >> $GITHUB_ENV
      - id: install-update-python-deps
        run: |
          pip install -U pip
          pip install -U -r requirements.txt
      - id: dbt-debug
        run: |
          dbt debug
          
      
      